artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/Kavya-sree/Datasets/main/StellarClassificationData.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/star_classification.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  cleaned_data_dir: artifacts/data_validation/cleaned_data.csv

  
