artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/Kavya-sree/Datasets/main/StellarClassificationData.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/star_classification.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  cleaned_data_dir: artifacts/data_validation/cleaned_data.csv

  
data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_validation/cleaned_data.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/normalized_train.csv
  test_data_path: artifacts/data_transformation/normalized_test.csv
  model_name: model.joblib


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/normalized_test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json

